version: 2.1
defaults: &defaults
  working_directory: ~/lumigo-node-wrapper
  docker:
    - image: lumigo/ci:latest
      auth:
        username: lumigo
        password: $DOCKERHUB_PASSWORD

orbs:
  lumigo-orb: lumigo/lumigo-orb@volatile

workflows:
  test-deploy:
    jobs:
    - test:
        filters:
          branches:
            ignore: master
    - lumigo-orb/be-deploy:
        filters:
          branches:
            ignore: master
        requires:
          - test
    - lumigo-orb/integration-test:
        deploy_spec: default
        tests_spec: testNormal
        filters:
          branches:
            ignore: master
        requires:
          - lumigo-orb/be-deploy
    - lumigo-orb/deploy:
        filters:
          branches:
            only: master
  version: 2
