version: 2.1

orbs:
  lumigo-orb: &lumigo_orb_version lumigo/lumigo-orb@volatile

defaults: &defaults
  docker:
  - image: lumigo/ci-ubuntu2204:latest
    auth:
      username: lumigo
      password: $DOCKERHUB_PASSWORD
  working_directory: ~/opentelemetry-js-distro

workflows:
  test-deploy:
    jobs:
    - lumigo-orb/print_orb_versions:
        lumigo_orb_version: *lumigo_orb_version

    - test:
        context: common
        filters:
          branches:
            ignore: main

    - lumigo-orb/is_environment_available:
        context: common
        skip_on_auto_test_update: true
        filters:
          branches:
            ignore: main

    - lumigo-orb/be-deploy:
        context: common
        skip_on_auto_test_update: true
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/pre_build_artifacts:
        context: common
        skip_on_auto_test_update: true
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/integration-test-prep:
        context: common
        pre_builds_available: true
        run_test_cleanup: false
        skip_on_auto_test_update: true
        requires:
          - lumigo-orb/be-deploy
          - lumigo-orb/pre_build_artifacts

    - lumigo-orb/integration-test-cleanup:
        name: pre-test-cleanup
        context: common
        skip_on_auto_test_update: true
        requires:
          - lumigo-orb/integration-test-prep

    - lumigo-orb/integration-test-parallel:
        context: common
        run_test_cleanup: false
        skip_on_auto_test_update: true
        requires:
          - pre-test-cleanup

    - lumigo-orb/integration-test-cleanup:
        name: post-test-cleanup
        context: common
        skip_on_auto_test_update: true
        requires:
          - lumigo-orb/integration-test-parallel

    - lumigo-orb/e2e-test:
        context: common
        skip_on_auto_test_update: true
        requires:
          - pre-test-cleanup

    - lumigo-orb/workflow-completed-successfully:
        context: common
        skip_on_auto_test_update: true
        requires:
          - test
          - lumigo-orb/integration-test-parallel
          - lumigo-orb/e2e-test

    - deploy:
        context:
          - common
          - node.js
        filters:
          branches:
            only: main

jobs:
  test:
    <<: *defaults
    environment:
      - TZ: Asia/Jerusalem
      - NODE_OPTIONS: --max_old_space_size=1500
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: prettier
          command: npm run prettier:ci
      - run:
          name: run checks script
          command: ./scripts/checks.sh
      - run:
          name: test
          command: npm run test:unit
      - run:
          name: eslint
          command: npm run lint
      - run:
          name: code-coverage
          command: npm test --coverage && codecov
      - store_artifacts:
          path: coverage
          prefix: coverage

  deploy:
    <<: *defaults
    environment:
      - TZ: Asia/Jerusalem
    resource_class: medium+
    steps:
      - lumigo-orb/checkout_utils
      - checkout
      - run:
          name: Check if tagged
          command: |
            tags=$(git tag -l --points-at HEAD)
            echo "Tags $tags"
            if [[ ! -z "$tags" ]]
            then
              echo "A tagged commit, skip..."
              circleci step halt
            fi
      - run:
          name: deploy to npm
          command: ./scripts/bd_to_prod.sh
