import { init, LumigoSdkInitialization } from './distro';
import { logger } from './logging';

let lumigoSdk: LumigoSdkInitialization | undefined;

(async () => {
  logger.info('Lumigo OpenTelemetry Distro synchronous bootstrapping starting...');
  lumigoSdk = await init;
})();

/*
  The `export =` syntax makes sure that using the sync endpoint from both TS and JS will return the same object structure:

    // TS
    import lumigoSdk from '@lumigo/opentelemetry/sync';

    // JS
    const lumigoSdk = require('@lumigo/opentelemetry/sync');

  Using `export default lumigoSdk` would have made the JS usage look like this:

    // JS code generated by TS would have a `default` property for interoperability
    const { default: lumigoSdk } = require('@lumigo/opentelemetry/sync');
 */
export = lumigoSdk;
