name: Check PR title format

on:
    pull_request:
        # Every pull request type
        types:
            - opened
            - reopened
            - synchronize
            - closed
            - edited

jobs:
    # Job that checks the title of the PR & makes sure it fits the semantic versioning format
    check-pr-title:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR Title
              uses: actions/github-script@v6
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const title = context.payload.pull_request.title;
                      const regex = /^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(\([a-z0-9-]+\))?: .{1,50}/;
                      if (!regex.test(title)) {
                          core.setFailed(`PR title "${title}" is not in the correct format. Please use the following format: <type>(<scope>): <description>`);
                      }
